//<auto-generated />

using System.Threading.Tasks;
using Entities;
using Refit;

namespace Web.Services
{
    public interface ICartItemApi
    {
        [Post("/CartItem/Add")]
        Task<CartItem> Add([Body] CartItem cartItem);
    }
}