//<auto-generated />

using System.Collections.Generic;
using System.Threading.Tasks;
using Core.Entities;
using Entities;
using Refit;

namespace Web.Services
{
    public interface IVehicleApi
    {
        [Get("/Vehicle/GetBrandList")]
        Task<IEnumerable<DropDownDtos>> GetBrandList();

        [Get("/Vehicle/GetCars")]
        Task<IEnumerable<Vehicle>> GetCars();

        [Post("/Vehicle/GetCars/{startIndex},{count}")]
        Task<IEnumerable<Vehicle>> GetCars(int startIndex, int count, string brandName = null);

        [Get("/Vehicle/GetById/{id}")]
        Task<Vehicle> GetById(int id);

        [Get("/Vehicle/GetCountList")]
        Task<int> GetCountList(string brandName = null);
    }
}